<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tahun_ajaran extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tahun_ajaran_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('tahun_ajaran/tahun_ajaran_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Tahun_ajaran_model->json();
    }

    public function read($id) 
    {
        $row = $this->Tahun_ajaran_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_ta' => $row->id_ta,
		'tahun' => $row->tahun,
		'deskripsi' => $row->deskripsi,
		'status' => $row->status,
	    );
            $this->load->view('tahun_ajaran/tahun_ajaran_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tahun_ajaran'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('tahun_ajaran/create_action'),
	    'id_ta' => set_value('id_ta'),
	    'tahun' => set_value('tahun'),
	    'deskripsi' => set_value('deskripsi'),
	    'status' => set_value('status'),
	);
        $this->load->view('tahun_ajaran/tahun_ajaran_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'tahun' => $this->input->post('tahun',TRUE),
		'deskripsi' => $this->input->post('deskripsi',TRUE),
		'status' => $this->input->post('status',TRUE),
	    );

            $this->Tahun_ajaran_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('tahun_ajaran'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Tahun_ajaran_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('tahun_ajaran/update_action'),
		'id_ta' => set_value('id_ta', $row->id_ta),
		'tahun' => set_value('tahun', $row->tahun),
		'deskripsi' => set_value('deskripsi', $row->deskripsi),
		'status' => set_value('status', $row->status),
	    );
            $this->load->view('tahun_ajaran/tahun_ajaran_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tahun_ajaran'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_ta', TRUE));
        } else {
            $data = array(
		'tahun' => $this->input->post('tahun',TRUE),
		'deskripsi' => $this->input->post('deskripsi',TRUE),
		'status' => $this->input->post('status',TRUE),
	    );

            $this->Tahun_ajaran_model->update($this->input->post('id_ta', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('tahun_ajaran'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Tahun_ajaran_model->get_by_id($id);

        if ($row) {
            $this->Tahun_ajaran_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('tahun_ajaran'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tahun_ajaran'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('tahun', 'tahun', 'trim|required');
	$this->form_validation->set_rules('deskripsi', 'deskripsi', 'trim|required');
	$this->form_validation->set_rules('status', 'status', 'trim|required');

	$this->form_validation->set_rules('id_ta', 'id_ta', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Tahun_ajaran.php */
/* Location: ./application/controllers/Tahun_ajaran.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-01-21 13:31:50 */
/* http://harviacode.com */