<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Transkrip extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Transkrip_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('transkrip/transkrip_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Transkrip_model->json();
    }

    public function read($id) 
    {
        $row = $this->Transkrip_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_transkrip' => $row->id_transkrip,
		'nim' => $row->nim,
		'id_jurusan' => $row->id_jurusan,
	    );
            $this->load->view('transkrip/transkrip_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('transkrip'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('transkrip/create_action'),
	    'id_transkrip' => set_value('id_transkrip'),
	    'nim' => set_value('nim'),
	    'id_jurusan' => set_value('id_jurusan'),
	);
        $this->load->view('transkrip/transkrip_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nim' => $this->input->post('nim',TRUE),
		'id_jurusan' => $this->input->post('id_jurusan',TRUE),
	    );

            $this->Transkrip_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('transkrip'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Transkrip_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('transkrip/update_action'),
		'id_transkrip' => set_value('id_transkrip', $row->id_transkrip),
		'nim' => set_value('nim', $row->nim),
		'id_jurusan' => set_value('id_jurusan', $row->id_jurusan),
	    );
            $this->load->view('transkrip/transkrip_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('transkrip'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_transkrip', TRUE));
        } else {
            $data = array(
		'nim' => $this->input->post('nim',TRUE),
		'id_jurusan' => $this->input->post('id_jurusan',TRUE),
	    );

            $this->Transkrip_model->update($this->input->post('id_transkrip', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('transkrip'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Transkrip_model->get_by_id($id);

        if ($row) {
            $this->Transkrip_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('transkrip'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('transkrip'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nim', 'nim', 'trim|required');
	$this->form_validation->set_rules('id_jurusan', 'id jurusan', 'trim|required');

	$this->form_validation->set_rules('id_transkrip', 'id_transkrip', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Transkrip.php */
/* Location: ./application/controllers/Transkrip.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-01-21 13:34:30 */
/* http://harviacode.com */